- hosts: all
  gather_facts: false
  collections:
    - awx.awx
  tasks:
    - name: Add inventory
      inventory:
         name: "Foo Inventory"
         description: "Our Foo Cloud Servers"
         organization: "Bar Org"
         state: present
         tower_username: admin
         tower_password: redhat
         tower_host: 192.168.56.114
