---
- name: Change Power State of All Azure VMs
  hosts: localhost
  gather_facts: False

  vars:
    # yes / no
    - new_power_state: 'yes'

  tasks:
    - name: allocate / de-allocate virtual machines
      azure.azcollection.azure_rm_virtualmachine:
        # resourece_group and name are dynamically populated during inventory scan
        resource_group: "main"
        name: "myvm"
        allocated: 1
      delegate_to: localhost
...
