---
- name: Fetch filebeat.yml from remote hosts
  hosts: all
  tasks:
    - name: Fetch /etc/filebeat/filebeat.yml
      fetch:
        src: /etc/filebeat/filebeat.yml
        dest: /root/testing/
        #flat: yes
