---
- name: test play
  hosts: all
  tasks:

  - name: template a file
    ansible.builtin.template:
       src: /mytemplates/foo.j2
       dest: /tmp/test
       owner: root
       group: root
       mode: '0600'
...
