- hosts: all
  gather_facts: true
  collections:
    - ansible.tower
  tasks:
    - tower_job_list:
        status: successful
        tower_host: localhost
        tower_username: admin
        tower_password: redhat
        validate_certs: no
        
    - set_fact:
        job_id: "{{ lookup('env', 'JOB_ID') | int }}"

    - set_fact:
        job_api: "{{ lookup('ansible.tower.tower_api', 'jobs/{{ job_id }}', verify_ssl=False) }}"

    - debug:
        var: job_api.execution_node
