- hosts: all
  vars:
      - myname: "komal"
  tasks:
  - name: Check for the extra_var
    command: date
    register: datea
    diff: true
    tags:
      - datea
       
  #- command: sleep 20h
  #  register: sleep
  #  tags:
  #    - sleep
  
  - command: date
    register: dateb
    tags:
      - dateb
   
  - debug:
       msg: "This is the user: {{ tower_user_name }}"
       
  - debug:
       msg: "{{ myname }}"
     
  - debug:
       var: tower_job_launch_vars['limit_value']
       
  - name: download fim report- original fetch module
    fetch:
      src: "/tmp/tom/test.txt"
      dest: "/var/lib/awx/test.txt"
      flat: yes
    check_mode: no
    #changed_when: false
