- hosts: all
  vars:
      - myname: "komal is very nice"
  tasks:
  - name: Check for the extra_var
    command: date
    register: datea
    tags:
      - datea
       
  #- command: sleep 20h
  #  register: sleep
  #  tags:
  #    - sleep
  
  - command: date
    register: dateb
    tags:
      - dateb
   
  - debug:
       msg: "This is the user: {{ tower_user_name }}"
       
  - debug:
       msg: "{{ myname }}"
     
  - debug:
       var: vm_hostname 
