- hosts: all
  vars:
      - myname: "komal"
  tasks:
  - name: Check for the extra_var
    command: date
    register: datea
    diff: true
    tags:
      - datea
       
  #- command: sleep 20h
  #  register: sleep
  #  tags:
  #    - sleep
  
  - command: date
    register: dateb
    tags:
      - dateb
   
  - debug:
       msg: "This is the user: {{ tower_user_name }}"
       
  - debug:
       msg: "{{ myname }}"
     
  - debug:
       var: tower_job_extra_vars['limit']
       
  - name: Fetch job template details
    uri:
      url: "http://localhost/api/v2/job_templates/7/"
        method: GET
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer AEeIM4tFpLphP9EdC50wgBmRw2St1l"
    register: job_template_result

  - name: Display job template limit
      debug:
        var: job_template_result.json.limit
       
  - name: download fim report- original fetch module
    fetch:
      src: "/tmp/tom/test.txt"
      dest: "/var/lib/awx/test.txt"
      flat: yes
    check_mode: no
    #changed_when: false
