- hosts: all
  vars:
      - myname: "ruchu is very nice"
  tasks:
  - name: Check for the extra_var
    command: "echo {{ nameme }}"
    register: myname
    tags:
      - name
    
  - debug:
       var: myname
     
