- hosts: all
  vars:
      - myname: "komal is very nice"
  tasks:
  - name: Check for the extra_var
    command: "echo {{ myname }}"
    register: myname
    tags:
      - name
  - command: "sleep 30"
      
  - debug:
       var: myname
    
  - debug:
       msg: "This is the user: {{ tower_user_name }}"
     
