- hosts: all
  vars:
      - nameme: "ruchu is very nice"
  tasks:
  - name: Checking via the command ping
    command: 'ping localhost'
    register: myconfig
    tags:
    - pinging
    - ping
    
  - name: Check for the extra_var
    command: "echo {{ nameme }}"
    register: myname
    tags:
      - name
    
  - debug:
       var: myname
     
