- hosts: all
  vars:
      - myname: "komal is very nice"
  tasks:
  - name: Check for the extra_var
    command: "echo {{ myname }}"
    register: myname
    tags:
      - name
      
  - debug:
       msg: "{{ tower_group }}"
       
  - debug:
       msg: "{{ tower_user_group }}"
    
  - debug:
       msg: "This is the user: {{ tower_user_name }}"
     
