---

- hosts: localhost
  gather_facts: false

  vars:
    msg: 'hello'

  tasks:
    - debug:
        var: msg
  
    - command: 'ansible-runner run -i localhost --playbook debug.yml'
      register: output

    - debug:
        var: output.stdout_lines
