- name: root login enabled
  hosts: localhost
  gather_facts: false
  tasks:
  - name: ssh PermitRootlogin
    ansible.builtin.lineinfile:
       dest: /etc/ssh/sshd_config
       regexp: '^PermitRootLogin'
       line: "PermitRootLogin no"
       state: present
    notify: ssh restart
  
  handlers:
  - name: ssh restart
    ansible.builtin.service:
        name: sshd
        state: restarted
