- hosts: all
  vars:
      - myname: "komal "
  tasks:
  #- name: Install the 'Development tools' package group
  #  ansible.builtin.yum:
  #    name: "@Development tools"
  #    state: remove
      
  - name: Install the '@postgresql:9.6' module stream
    ansible.builtin.dnf:
       name: "@postgresql:9.6"
       state: absent
       autoremove: yes
