- hosts: localhost
  vars:
      - myname: "komal is very nice"
  tasks:
  - name: Install the '@postgresql:9.6' module stream
    ansible.builtin.yum:
       name: "@postgresql:9.6"
       state: present
