- hosts: all
  gather_facts: no
  vars:
    visa_soe: false
  tasks:
  - name: Clear existing facts
    meta: clear_facts
    ignore_errors: yes
    
  - name: Make Cachable on tower - CMDB Facts on all servers
    set_fact:
          visa_soe: "{{ visa_soe | default ('false')}}"
          cacheable: yes
    ignore_errors: yes
