- name: set a variable for later use
  hosts: all

  tasks:
    - name: register some value to test in later playbook run
      set_stats:
        data:
          jobid: "{{ tower_user_id }}"
        aggregate: no
        
    - name: debug the value
      debug:
        var: "{{ tower_user_id }}"

- name: Print uptime on hosts
  hosts: all
  tasks:
    - name: print uptime
      ansible.builtin.shell: uptime
