---
- name: tower_job_list module
  hosts: all
  collections:
    - ansible.controller
  tasks:
    - name: Add user
      user:
          username: ruchika
          password: ruchika
          email: ruchika@gmail.com
          first_name: Ruchika
          last_name: Suthar
          state: present
          controller_host: "{{ controller_node }}"
          controller_username: "admin"
          controller_password: "redhat"
          controller_oauthtoken: "{{ controller_token }}"
          validate_certs: no
          
    - name: Create Ping job template
      job_template:
          name: "Ping"
          job_type: "run"
          organization: "Default"
          inventory: "Demo Inventory"
          project: "Demo Project"
          playbook: "index.yml"
          credentials:
             - "Demo Credential"
          state: "present"
          controller_host: "{{ controller_node }}"
          controller_username: "admin"
          controller_password: "redhat"
          controller_oauthtoken: "{{ controller_token }}"
          validate_certs: no
          survey_enabled: yes
          #survey_spec: "{{ lookup('file', 'try.yaml') }}" 
          #survey_spec: "{{ lookup('file', '{{ playbook_dir }}/{{ try.yaml}}') }}"
          survey_spec:
             name: 'Host Onboard Survey'
             description: ''
             spec: &survey_spec
             - question_name: What host are we going to onboard?
               question_description: ''
               required: true
               type: text
               variable: host_onboard_hostname
               min: 3
               max: 1024
               default: ''
               choices: ''
               new_question: true
             - <<: *survey_spec
               question_name: What is the application we are onboarding?
               variable: host_onboard_application
             - <<: *survey_spec
               question_name: What is the host environment we are onboarding?
               variable: host_onboard_environment
