---
- name: tower_job_list module
  hosts: all
  collections:
    - ansible.controller
  tasks:
    - name: Add user
      user:
          username: ruchika
          password: ruchika
          email: ruchika@gmail.com
          first_name: Ruchika
          last_name: Suthar
          state: present
          controller_host: "{{ controller_node }}"
          controller_username: "admin"
          controller_password: "redhat"
          controller_oauthtoken: "{{ controller_token }}"
          validate_certs: no
