---
- name: tower_job_list module
  hosts: all
  collections:
    - ansible.controller
  tasks:
    - name: delete host
      ansible.controller.host:
          name: 1.2.3.4
          inventory: "test"
          state: absent
          controller_host: "{{ controller_node }}"
          controller_username: "admin"
          controller_password: "redhat"
          validate_certs: false
          diff: true


    - name: Add user
      user:
          username: ruchika
          password: ruchika
          email: ruchika@gmail.com
          first_name: Ruchika
          last_name: Suthar
          state: present
          controller_host: "{{ controller_node }}"
          controller_username: "admin"
          controller_password: "redhat"
          controller_oauthtoken: "{{ controller_token }}"
          validate_certs: no
          
    - name: Create Ping job template
      job_template:
          name: "Ping"
          job_type: "run"
          organization: "Default"
          inventory: "Demo Inventory"
          project: "Demo Project"
          playbook: "index.yml"
          credentials:
             - "Demo Credential"
          state: "present"
          controller_host: "{{ controller_node }}"
          controller_username: "admin"
          controller_password: "redhat"
          controller_oauthtoken: "{{ controller_token }}"
          validate_certs: no
          survey_enabled: yes
          #survey_spec: "{{ lookup('file', 'my_survey.yaml') }}" 
          survey_spec: "{{ lookup('file', 'my_survey.yaml') | from_yaml }}"
          #survey_spec: "{{ lookup('file', '{{ playbook_dir }}/{{ try.yaml}}') }}"
          
