---
- name: tower_job_list module
  hosts: all
  collections:
    - ansible.controller
  tasks:
    - job_list:
        status: successful
        tower_host: "192.168.56.39"
        tower_username: admin
        tower_password: redhat
        validate_certs: no
