---
- name: tower_job_list module
  hosts: all
  collections:
    - ansible.controller
  tasks:
    - job_list:
        status: successful
        controller_host: "{{ controller_node }}"
        controller_username: admin
        controller_password: redhat
        controller_oauthtoken: "HSy8PXGT8hk3HjEtNboUsPbHAYLL8j"
        validate_certs: no
