---

- name: Hello Controller
  hosts: all
  sources:
     - ansible.eda.range:
         limit: 5

 #   - ansible.eda.webhook:
 #       host: 0.0.0.0
 #       port: 5000
  rules:
    - name: "Run Job Template"
 #    condition: event.payload is defined
      condition: event.i == 1
      action:
        run_job_template:
          name: "eda test"
          organization: Default
          job_args:
            extra_vars:
              data: "{{ event }}"
          retries: 1
          delay: 10
...
